### ISSUE TITLE
retrieve the webpack.config.js config file from the component to test

### ISSUE THREAD

**Issue by fabienjuif** [Zenika/react-workbench#17]
retrieve the webpack.config.js config file from the component to test
https://github.com/Zenika/react-workbench/pull/15

**Comment by fabienjuif** [comment]
And remove the "force push" of 'src' and 'styles'

**Comment by fabienjuif** [comment]
Firstly : retrieve these informations from a regexp
Long term : retrieve it from AST

**Comment by fabienjuif** [comment]
What about using react-scripts at first @bpetetot ?

**Comment by bpetetot** [comment]
Yes it could be a good start.
Watch also how it's done in storybook:
https://github.com/storybooks/storybook/blob/master/app/react/src/server/config.js

**Comment by fabienjuif** [comment]
pseudo-code (fr)
```
  // [x] retrouver le projet du composant
  // identifier la configuration webpack.config.js
    // soit via react-scripts
    // soit via webpack.config.js (à la racine)
    // soit demander via CLI à l'utilisateur
  // changer la conf du webpack.config.js retrouvé
    // entry
    // output
  // changer de contexte d'excution (dans le projet avec package.json)
  // executer webpack -p du projet testé
  // changer le contexte sur react-workbench
  // ?? CSS ???
  // executer notre webpack
```
