### ISSUE TITLE
1./2. | hoc-dat-gui

### ISSUE THREAD

**Issue by fabienjuif** [Zenika/react-workbench#2]
- [x] `hoc-dat-gui` : generate the gui to test a component, configuration is manually set
 - [ ] `hoc-dat-gui/auto` : generate the gui from propTypes, automatically

**Comment by fabienjuif** [comment]
https://github.com/Zenika/hoc-react-datgui

**Comment by bpetetot** [comment]
`hoc-dat-gui/auto` can't be done in the HOC because `react-docgen` must access to the source code of the wrapped component. This work must be done in `react-workbench`

**Comment by bpetetot** [comment]
1. and 2. done in PR #5 (using `babel-plugin-react-docgen`)
