### ISSUE TITLE
GUI / Tabs (right) / Props

### ISSUE THREAD

**Issue by fabienjuif** [Zenika/react-workbench#41]
#40

**Comment by bpetetot** [comment]
Manage all PropTypes in props updaters : 
- [ ] `array` => input type "text"
- [x] `bool` => checkbox
- [x] `func` => button
- [ ] `number` =>   input type "number"
- [x] `object` =>  input type "text"
- [ ] `string` =>  input type "text"
- [ ] `symbol` =>  input type "text"
- [ ] `node` =>  input type "text" (manage as `javascript array`)
- [ ] `element` => input type "text" (manage as `HTML elements`) ?
- [ ] `instanceOf(XXX)` => input type "text" (manage as `javascript object`)
- [ ] `oneOf([...])` => input type "select"
- [ ] `oneOfType([...])` => first resolved type
- [ ] `arrayOf` => input type "text" (manage as `javascript array`)
- [ ] `objectOf` => input type "text" (manage as `javascript object`)
- [ ] `shape` => input type "text" (manage as `javascript object`)
- [ ]  `any` => _can't be updated with an HTML element_
- [ ]  `custom` => _can't be updated with an HTML element_

**Comment by fabienjuif** [comment]
- `bool ` is handled end to end
 - `object` is handled at loading
 - `func` is handled at loading

**Comment by fabienjuif** [comment]
#53 
 - func
 - object
