### ISSUE TITLE
Remove hoc-dat-gui and use extracted props directly from docgen

### ISSUE THREAD

**Issue by bpetetot** [Zenika/react-workbench#46]
With the new GUI of Workbench, `hoc-dat-gui` is not appropriate to generate GUI updater for props. It will be much more flexible, maintainable and consistent to manage our own updater.

**To do it, we need to :**
- [x] get prop types with docgen
- [x] create props updater components from docgen
- [x] apply updates to the tested component (communication with redux)

**Comment by fabienjuif** [comment]
#41 
#43
