### ISSUE TITLE
Change internal state

### ISSUE THREAD

**Issue by fabienjuif** [Zenika/react-workbench#59]

**Comment by bpetetot** [comment]
how it's done in react-devtools : 
https://github.com/facebook/react-devtools/blob/master/backend/getData.js

**Comment by fabienjuif** [comment]
Or with enzyme: 
 - https://github.com/airbnb/enzyme/blob/master/src/ReactWrapperComponent.jsx
 - https://github.com/airbnb/enzyme/blob/master/src/ReactWrapper.jsx

https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/setState.md
