### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by fabienjuif** [Zenika/react-workbench#6]
Write scripts tests

**Comment by fabienjuif** [comment]
@fabienjuif one test for API , one for component
@bpetetot others

**Comment by fabienjuif** [comment]
@fabienjuif activate coveralls

**Comment by fabienjuif** [comment]
47% coverage :) 
https://coveralls.io/github/Zenika/react-workbench?branch=master

What are the slackers : 
 - api/models/fs/service.js : https://coveralls.io/builds/11465501/source?filename=src%2Fserver%2Fapi%2Fmodels%2Ffs%2Fservice.js
 - api/ddb/ddb : https://coveralls.io/builds/11465501/source?filename=src%2Fserver%2Fapi%2Fddb%2Fddb.js
 - api/docgen/service : https://coveralls.io/builds/11465501/source?filename=src%2Fserver%2Fapi%2Fmodels%2Fdocgen%2Fservice.js

**Comment by bpetetot** [comment]
**must** resolve #72 before closing this one
